### ISSUE TITLE
Redux-saga

### ISSUE THREAD

**Issue by benstoltz** [AltSchool/ember-cli-redux#4]
Thoughts on https://github.com/yelouafi/redux-saga instead of redux-thunk?

**Comment by matthewconstantine** [comment]
@benstoltz Thanks for the question. `redux-thunk` is just a basic middleware added by default. It seemed like a reasonable starting point without adding too much cognitive overhead.

Starting with version 0.2.0 you can choose different middleware. Following the [Customizing Middleware example](https://github.com/AltSchool/ember-cli-redux#customizing-middleware) in the Readme, it should be possible to swap out thunk for saga. Let me know how it goes, especially if you run into any problems with the configurable middleware.
